package com.example.myfood.model.dummy

import com.example.myfood.R
import com.example.myfood.model.data.FoodDetail
import com.example.myfood.model.data.ListFood
import com.example.myfood.model.data.OtherFoods

object FoodData {

     val foods = arrayListOf(
         FoodDetail("F001", name = "Bebek Betutu", price = "IDR 19000",typicalFood = "Bali", description = "Bebek Betutu adalah masakan kebanggan masyarakat Bali lho Grameds. Oleh karena itu kita dapat dengan mudah menemukan restoran yang menyajikan olahan dari bebek ini.\nCara masak Bebek Betutu ini menggunakan bebek utuh yang dibungkus daun pisang, lalu dibungkus lagi dengan pelepah pinang hingga rapat. Yang uniknya lagi adalah bebek tersebut ditanam dalam lubang di tanah dan ditutup dengan bara api selama 6 – 7 jam hingga daging bebek lunak dan empuk.", taste = 4f,rating = 4.5f, image = R.drawable.bebek_betutu, ingredients = "Terasi, sangrai, Bubuk Ketumbar, Daun Jeruk Purut, Bubuk Pala",otherFoods  = listOf( OtherFoods(foodId = "F002", name = "Pempek", image = R.drawable.pempek),OtherFoods(foodId = "F003", name = "Gudeg", image = R.drawable.gudeg), OtherFoods(foodId = "F004", name = "Rawon", image = R.drawable.rawon))),
         FoodDetail("F002", name = "Pempek", price = "IDR 15000",typicalFood = "Palembang", description = "Pempek merupakan kuliner khas Sumatra yang terbuat dari ikan tenggiri, toman, atau gabus yang dihaluskan, dicampur bersama tepung sagu dan bumbu halus. Pempek diuleni hingga kalis lalu direbus dalam air mendidih. setelah itu pempek digoreng dan disantap bersama kuah cuko. Kuah cuko adalah kuah yang terbuat dari rebusan gula merah dan cuka.", taste = 4.5f,rating = 5f, image = R.drawable.pempek, ingredients = "Ikan Tenggiri, Tepung Sagu, Cuka, Gula Merah",otherFoods  = listOf( OtherFoods(foodId = "F008", name = "Lumpia", image = R.drawable.lumpia),OtherFoods(foodId = "F006", name = "Sop Konro", image = R.drawable.sop_konro), OtherFoods(foodId = "F004", name = "Rawon", image = R.drawable.rawon))),
         FoodDetail("F003", name = "Gudeg", price = "IDR 10000",typicalFood = "Yogyakarta", description = "Gudeng merupakan makanan khas Yogyakarta yang terbuat dari nangka muda yang dimasak dengan santan dan daun jati selama berjam-jam hingga lembut dan bumbu meresap sempurna dan berwarna kemerahan.\nGudeg memiliki citasrasa manis dan sering disantap bersama kuah santan kental (areh), ayam kampung, telur, tahu tempe serta krecek. Meskipun pada dasarnya bukan termasuk makanan yang tahan lama, gudeg dapat kita temukan dalam berbentuk kaleng agar bisa tahan lebih lama untuk dibawa ke luar kota.", taste = 5f,rating = 5f, image = R.drawable.gudeg, ingredients = "Tempe, Sambel Cabe, Telur, Ayam Kampung",otherFoods  = listOf( OtherFoods(foodId = "F002", name = "Pempek", image = R.drawable.pempek),OtherFoods(foodId = "F005", name = "Woku Belanga", image = R.drawable.woku_belanga), OtherFoods(foodId = "F001", name = "Bebek Betutu", image = R.drawable.bebek_betutu))),
         FoodDetail("F004", name = "Cakalang Rica-Rica", price = "IDR 24000",typicalFood = "Manado", description = "Cakalang rica-rica merupakan kuliner khas Manado yang terkenal akan kelezatannya.\nKuliner yang memiliki citarasa pedas ini terbuat dari ikan cakalang yang diasap hingga harum dan bertekstur kering. Ikan cakalang tersebut disuwir, diberi perasan jeruk nipis dan dan garam, lalu ditumis bersama sambal rica", taste = 4f,rating = 4f, image = R.drawable.cakalang_rica_rica, ingredients = "Jeruk Nipis, Sambal Rica-Rica",otherFoods  = listOf( OtherFoods(foodId = "F002", name = "Pempek", image = R.drawable.pempek),OtherFoods(foodId = "F010", name = "Mie Aceh", image = R.drawable.mie_aceh), OtherFoods(foodId = "F009", name = "Lumpia", image = R.drawable.lumpia))),
         FoodDetail("F005", name = "Woku Belanga", price = "IDR 17000",typicalFood = "Manado", description = "Woku Belanga adalah bumbu makanan ala Manado yang terbuat dari berbagai macam bumbu khas Minahasa. Bumbu khas ini dimasak dalam belanga, oleh karena itu terkenal dengan sebutan woku balanga.\nBumbu woku terdiri dari bawang merah, bawang putih, cabai rawit, tomat, kunyit, jahe, serai, daun pandan, daun jeruk, daun kemangi dan daun bawang. Tak mengherankan jika woku memiliki aroma khas yang harum.", taste = 4f,rating = 5f, image = R.drawable.woku_belanga, ingredients = "Cabai Rawit, Tomat, Kunyit, Jahe, Serai, ",otherFoods  = listOf( OtherFoods(foodId = "F007", name = "Rawon", image = R.drawable.rawon),OtherFoods(foodId = "F001", name = "Bebek Betutu", image = R.drawable.bebek_betutu), OtherFoods(foodId = "F003", name = "Gudeg", image = R.drawable.gudeg))),
         FoodDetail("F006", name = "Sop Konro", price = "IDR 25000",typicalFood = "Sulawesi Selatan", description = "Sup Konro adalah masakan yang terbuat dari iga sapi khas Makasar, Sulawesi Selatan. Sup ini memiliki tekstur kuah yang kental berwarna coklat kehitaman. Warna coklat kehitaman diperoleh dari buah kluwek dan rasa yang kuat karena penambahan ketumbar.", taste = 4f,rating = 5f, image = R.drawable.sop_konro, ingredients = "Pala, Kunyit, Kencur, Kayu Manis",otherFoods  = listOf( OtherFoods(foodId = "F007", name = "Rawon", image = R.drawable.rawon),OtherFoods(foodId = "F010", name = "Mie Aceh", image = R.drawable.mie_aceh), OtherFoods(foodId = "F001", name = "Bebek Betutu", image = R.drawable.bebek_betutu))),
         FoodDetail("F007", name = "Rawon", price = "IDR 15000",typicalFood = "Surabaya", description = "Rawon adalah makan khas dari Kota Surabaya yang mirip dengan sup daging namun memiliki kuah hitam pekat. Meskipun kuahnya tidak seperti sup pada umumnya, rawon memiliki cita rasa yang khas dan selalu dirindukan oleh penikmat masakan Jawa timuran.", taste = 4f,rating = 4f, image = R.drawable.rawon, ingredients = "Seledri, Bombay",otherFoods  = listOf( OtherFoods(foodId = "F002", name = "Pempek", image = R.drawable.pempek),OtherFoods(foodId = "F009", name = "Bika Ambon", image = R.drawable.bika_ambon), OtherFoods(foodId = "F010", name = "Mie Aceh", image = R.drawable.mie_aceh))),
         FoodDetail("F008", name = "Lumpia", price = "IDR 10000",typicalFood = "Semarang", description = "Lumpia atau lunpia adalah makanan khas Semarang yang sering disajikan untuk camilan sore atau sebagai makanan ringan. Lumpia merupakan makanan sejenis rolade berisi rebung atau bambu muda. Tersedia banyak varian isi lumpia, mulai dari telur, daging ayam, ataupun udang.", taste = 4f,rating = 3f, image = R.drawable.lumpia, ingredients = "Seledri, Bombay",otherFoods  = listOf( OtherFoods(foodId = "F001", name = "Bebek Betutu", image = R.drawable.bebek_betutu),OtherFoods(foodId = "F003", name = "Gudeh", image = R.drawable.gudeg), OtherFoods(foodId = "F009", name = "Bika Ambon", image = R.drawable.bika_ambon))),
         FoodDetail("F009", name = "Bika Ambon", price = "IDR 15000",typicalFood = "Medan", description = "Makanan yang identik dengan warna kuning dan sering digunakan untuk oleh-oleh adalah bika ambon. Meskipun namanya memuat kata ‘ambon’, makanan ini berasal dari Sumatera Utara. Makanan ini terbuat dari gula, santan, serta telur. Bika ambon digemari berbagai kalangan masyarakat karena rasanya yang lezat. ", taste = 4f,rating = 5f, image = R.drawable.bika_ambon, ingredients = "Pandan, Gula, cokelat",otherFoods  = listOf( OtherFoods(foodId = "F005", name = "Woku Belanga", image = R.drawable.woku_belanga),OtherFoods(foodId = "F007", name = "Rawon", image = R.drawable.rawon), OtherFoods(foodId = "F006", name = "Sop Konro", image = R.drawable.sop_konro))),
         FoodDetail("F010", name = "Mie Aceh", price = "IDR 10000",typicalFood = "Aceh", description = "Makanan ini sangat mudah ditemukan di warung-warung yang ada di Aceh dengan harga terjangkau. Tidak hanya masyarakat Aceh saja yang menyukai mie ini, bahkan wisatawan dari luar Sumatera pun rela mengantre demi mencicipi kelezatannya.", taste = 4f,rating = 5f, image = R.drawable.mie_aceh, ingredients = "Tomat, Bawang Merah, Mie",otherFoods  = listOf( OtherFoods(foodId = "F002", name = "Bebek Betutu", image = R.drawable.bebek_betutu),OtherFoods(foodId = "F003", name = "Gudeg", image = R.drawable.gudeg), OtherFoods(foodId = "F008", name = "Lumpia", image = R.drawable.lumpia)))
     )

    val listData: ArrayList<ListFood>
        get() {
            val listFood = arrayListOf<ListFood>()
            foods.forEach {
                listFood.add(ListFood(foodId = it.foodId, name = it.name, price = it.price, image = it.image))
            }
            return listFood
        }
}